<a href="https://colab.research.google.com/github/Rakesh0430/CLIP/blob/main/Copy_of_word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#spacy, textblob, nltk
#https://radimrehurek.com/gensim/auto_examples/index.html
import gensim
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')


[============--------------------------------------] 25.6% 425.0/1662.8MB downloaded

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
!pip install wget

In [ ]:
!wget -c "https://github.com/mmihaltz/word2vec-GoogleNews-vectors/blob/master/GoogleNews-vectors-negative300.bin.gz"

--2024-02-10 06:27:01--  https://github.com/mmihaltz/word2vec-GoogleNews-vectors/blob/master/GoogleNews-vectors-negative300.bin.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.



In [ ]:
!gzip GoogleNews-vectors-negative300.bin.gz > GoogleNews-vectors-negative300.bin.gz

gzip: GoogleNews-vectors-negative300.bin.gz already has .gz suffix -- unchanged


In [ ]:
model=KeyedVectors.load_word2vec_format("/content/drive/MyDrive/GoogleNews-vectors-negative300.bin.gz",binary=True,limit=500000)

In [ ]:
model

In [ ]:
model["cricket"]

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [ ]:
len(model["cricket"])

300

In [ ]:
model["space"]

array([-0.11914062,  0.078125  ,  0.05566406, -0.06542969, -0.11523438,
       -0.19726562,  0.07373047, -0.03112793,  0.03930664, -0.13769531,
       -0.04833984, -0.06542969, -0.12304688, -0.14941406, -0.04467773,
       -0.06494141,  0.06542969,  0.11621094,  0.15820312,  0.09179688,
       -0.01409912, -0.14941406, -0.12255859, -0.01843262, -0.1015625 ,
        0.29101562, -0.05297852, -0.05981445,  0.0168457 , -0.25195312,
       -0.26171875, -0.01965332,  0.03662109, -0.0007782 , -0.06640625,
       -0.34960938,  0.03735352,  0.02502441,  0.00668335, -0.07177734,
       -0.10546875, -0.10351562,  0.19140625,  0.4296875 , -0.07080078,
       -0.05615234, -0.09082031,  0.203125  ,  0.06787109, -0.14355469,
        0.08935547, -0.09619141, -0.19726562, -0.16992188, -0.18164062,
       -0.15332031,  0.13769531, -0.08447266,  0.24121094, -0.02124023,
        0.08398438, -0.13574219, -0.05834961, -0.28710938, -0.23144531,
        0.03759766, -0.01611328, -0.078125  , -0.11132812,  0.18

In [ ]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035123825073)]

In [ ]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
model.most_similar("sunny")

[('balmy', 0.7314587831497192),
 ('sunshine', 0.7251086831092834),
 ('overcast', 0.6918097734451294),
 ('breezy', 0.6885849237442017),
 ('gloriously_sunny', 0.6779158711433411),
 ('sunny_skies', 0.6688455939292908),
 ('chilly', 0.66850346326828),
 ('windy', 0.6603769659996033),
 ('drizzly', 0.6585174202919006),
 ('sun_drenched', 0.6578938364982605)]

In [ ]:
model.most_similar("facebook")

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [ ]:
model.similarity('man','woman')

0.76640123

In [ ]:
model.similarity('man','java')

0.019312032

In [ ]:
model.similarity('man','python')

0.2097966

In [ ]:
model.similarity('man','php')

0.008337102

In [ ]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'C'

In [ ]:
model["woman"]

array([ 2.43164062e-01, -7.71484375e-02, -1.03027344e-01, -1.07421875e-01,
        1.18164062e-01, -1.07421875e-01, -1.14257812e-01,  2.56347656e-02,
        1.11816406e-01,  4.85839844e-02, -9.71679688e-02, -3.43750000e-01,
       -6.29882812e-02, -1.25000000e-01, -2.70996094e-02,  9.42382812e-02,
       -1.87500000e-01, -5.34667969e-02,  6.25000000e-02, -3.05175781e-02,
       -2.90527344e-02, -4.80957031e-02, -5.51757812e-02, -4.08203125e-01,
        1.01318359e-02, -2.32421875e-01, -1.70898438e-01,  2.63671875e-01,
        3.49609375e-01, -2.11914062e-01,  1.43554688e-01, -6.22558594e-03,
       -2.25585938e-01, -1.05468750e-01, -1.16210938e-01,  1.23046875e-01,
        3.06640625e-01, -4.88281250e-02, -9.57031250e-02,  1.99218750e-01,
       -1.57226562e-01, -2.80761719e-02,  1.58203125e-01, -2.42919922e-02,
        1.29882812e-01, -8.98437500e-02, -7.61718750e-02,  3.54003906e-02,
       -3.06396484e-02,  1.52343750e-01,  5.24902344e-02,  1.60980225e-03,
        5.56640625e-02,  

In [ ]:
vec=model['king'] - model['man'] + model['woman']

In [ ]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [ ]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [ ]:
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
import os

In [ ]:
story=[]

In [ ]:
for file in os.listdir("/content/data"):
  print(file)

001ssb[1].txt
003ssb[1].txt
002ssb[1].txt
004ssb[1].txt


In [ ]:
f=open("/content/data/001ssb[1].txt")
corpus=f.read()

In [ ]:
sent_cor=sent_tokenize(corpus)

In [ ]:
for i in sent_cor:
  print(simple_preprocess(i))

Streaming output truncated to the last 5000 lines.
['her', 'handmaids', 'and', 'the', 'men', 'of', 'her', 'khas', 'came', 'after', 'smiling', 'and', 'jesting', 'among', 'themselves']
['dothraki', 'hooves', 'had', 'torn', 'the', 'earth', 'and', 'trampled', 'the', 'rye', 'and', 'lentils', 'into', 'the', 'ground', 'while', 'arakhs', 'and', 'arrows', 'had', 'sown', 'terrible', 'new', 'crop', 'and', 'watered', 'it', 'with', 'blood']
['dying', 'horses', 'lifted', 'their', 'heads', 'and', 'screamed', 'at', 'her', 'as', 'she', 'rode', 'past']
['wounded', 'men', 'moaned', 'and', 'prayed']
['jaqqa', 'rhan', 'moved', 'among', 'them', 'the', 'mercy', 'men', 'with', 'their', 'heavy', 'axes', 'taking', 'harvest', 'of', 'heads', 'from', 'the', 'dead', 'and', 'dying', 'alike']
['after', 'them', 'would', 'scurry', 'flock', 'of', 'small', 'girls', 'pulling', 'arrows', 'from', 'the', 'corpses', 'to', 'fill', 'their', 'baskets']
['last', 'of', 'all', 'the', 'dogs', 'would', 'come', 'sniffing', 'lean', 'an

In [ ]:
for file in os.listdir("/content/data"):
  file_path=os.path.join("/content/data",file)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for i in raw_sent:
    story.append(simple_preprocess(i))

In [ ]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [ ]:
len(story)

115483

In [ ]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [ ]:
model=gensim.models.Word2Vec(window=10,min_count=5,vector_size=150)

In [ ]:
model.build_vocab(story)

In [ ]:
model.corpus_count

115483

In [ ]:
model.epochs

5

In [ ]:
model.corpus_total_words

1312415

In [ ]:
model.min_count

5

In [ ]:
model.train(story,total_examples=model.corpus_count,epochs=5)

(4900465, 6562075)

In [ ]:
len(model.wv['king'])

150

In [ ]:
model.wv.most_similar("king")

[('throne', 0.6934491991996765),
 ('baratheon', 0.6857103705406189),
 ('realm', 0.6705314517021179),
 ('tourney', 0.6542226076126099),
 ('council', 0.6541844606399536),
 ('prince', 0.6342549920082092),
 ('lannisters', 0.591943621635437),
 ('victory', 0.5876509547233582),
 ('queen', 0.5866008996963501),
 ('war', 0.584467887878418)]

In [ ]:
model.wv.get_normed_vectors().shape

(10176, 150)

In [ ]:
len(model.wv.index_to_key)

10176

In [ ]:
model.save("word2vec.model")

In [ ]:
model.save("word2vec.bin")

In [ ]:
!gzip word2vec.bin > word2vec.bin.gz

gzip: word2vec.bin.gz already exists; do you wish to overwrite (y or n)? 